name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.21.0
          cache: "yarn"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Build Python RPC with cx_Freeze
        run: python python_rpc/setup.py build

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: yarn build:linux

      - name: Build Windows
        if: matrix.os == 'windows-2022'
        run: yarn build:win

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
